package com.careflow.hospital.scheduling;

import com.careflow.hospital.appointments.*;
import com.careflow.hospital.departments.*;
import com.careflow.hospital.doctors.*;
import com.careflow.hospital.reservations.SlotReservationRepository;
import com.careflow.hospital.shared.DomainException;
import java.time.*; import java.util.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service public class SlotGenerationService {
  private final DepartmentRepository departments;private final DoctorRepository doctors;private final DoctorScheduleRepository schedules;private final DoctorScheduleExceptionRepository exceptions;private final AppointmentRepository appointments;private final SlotReservationRepository reservations;
  public SlotGenerationService(DepartmentRepository departments,DoctorRepository doctors,DoctorScheduleRepository schedules,DoctorScheduleExceptionRepository exceptions,AppointmentRepository appointments,SlotReservationRepository reservations){this.departments=departments;this.doctors=doctors;this.schedules=schedules;this.exceptions=exceptions;this.appointments=appointments;this.reservations=reservations;}
  @Transactional(readOnly=true) public List<SlotDtos.Slot> generate(UUID departmentId,UUID requestedDoctorId,LocalDate date){var department=departments.findById(departmentId).filter(Department::isActive).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"DEPARTMENT_NOT_FOUND","Department was not found."));ZoneId zone=zone(department.getTimezone());LocalDate today=LocalDate.now(zone);if(date.isBefore(today)||date.isAfter(today.plusDays(90)))throw new DomainException(HttpStatus.BAD_REQUEST,"DATE_OUTSIDE_BOOKING_WINDOW","Date must be within the next 90 days.");var candidates=doctors.findAllByDepartmentIdAndActiveTrueOrderByFullNameAsc(departmentId).stream().filter(d->requestedDoctorId==null||d.getId().equals(requestedDoctorId)).toList();if(requestedDoctorId!=null&&candidates.isEmpty())throw new DomainException(HttpStatus.NOT_FOUND,"DOCTOR_NOT_FOUND","Active doctor was not found in this department.");return candidates.stream().flatMap(d->slots(d,date,zone).stream()).sorted(Comparator.comparing(SlotDtos.Slot::startsAt).thenComparing(s->s.doctorName().toLowerCase(Locale.ROOT))).toList();}
  private List<SlotDtos.Slot> slots(Doctor doctor,LocalDate date,ZoneId zone){var ranges=new ArrayList<Range>();schedules.findAllByDoctorIdAndDayOfWeekAndActiveTrue(doctor.getId(),date.getDayOfWeek().getValue()).forEach(s->ranges.add(new Range(s.getStartsAt(),s.getEndsAt(),s.getSlotDurationMinutes())));var dayExceptions=exceptions.findAllByDoctorIdAndDate(doctor.getId(),date);dayExceptions.stream().filter(e->"AVAILABLE".equals(e.getType())).forEach(e->ranges.add(new Range(e.getStartsAt(),e.getEndsAt(),e.getSlotDurationMinutes())));Instant now=Instant.now(),dayStart=date.atStartOfDay(zone).toInstant(),dayEnd=date.plusDays(1).atStartOfDay(zone).toInstant();var busy=appointments.findActiveOverlaps(doctor.getId(),dayStart,dayEnd);var held=reservations.findActiveOverlaps(doctor.getId(),dayStart,dayEnd,now);var result=new LinkedHashMap<Instant,SlotDtos.Slot>();for(var range:ranges){for(LocalTime cursor=range.start;!cursor.plusMinutes(range.duration).isAfter(range.end);cursor=cursor.plusMinutes(range.duration)){LocalTime end=cursor.plusMinutes(range.duration);if(unavailable(cursor,end,dayExceptions))continue;Instant startInstant=ZonedDateTime.of(date,cursor,zone).toInstant(),endInstant=ZonedDateTime.of(date,end,zone).toInstant();if(!startInstant.isAfter(now)||busy.stream().anyMatch(a->startInstant.isBefore(a.getEndsAt())&&endInstant.isAfter(a.getStartsAt()))||held.stream().anyMatch(r->startInstant.isBefore(r.getEndsAt())&&endInstant.isAfter(r.getStartsAt())))continue;result.putIfAbsent(startInstant,new SlotDtos.Slot(doctor.getId(),doctor.getFullName(),doctor.getSpecialization(),startInstant,endInstant,range.duration,zone.getId()));}}return new ArrayList<>(result.values());}
  private boolean unavailable(LocalTime start,LocalTime end,List<DoctorScheduleException> values){return values.stream().filter(e->"UNAVAILABLE".equals(e.getType())).anyMatch(e->e.getStartsAt()==null||(start.isBefore(e.getEndsAt())&&end.isAfter(e.getStartsAt())));}
  private ZoneId zone(String value){try{return ZoneId.of(value);}catch(DateTimeException e){throw new DomainException(HttpStatus.INTERNAL_SERVER_ERROR,"INVALID_DEPARTMENT_TIMEZONE","Department timezone is invalid.");}}
  private record Range(LocalTime start,LocalTime end,int duration){}
}
