apiVersion: v1
kind: Secret
metadata:
  name: careflow-secrets
  namespace: careflow-hospital
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME_PRODUCTION_SECRET"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_PRODUCTION_SECRET"
  SECURITY_JWT_SECRET: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
