package com.careflow.hospital.intelligence;

import tools.jackson.databind.*;import tools.jackson.databind.node.ObjectNode;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.time.Duration;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.ResponseEntity;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/intelligence")
public class IntelligenceController {
 private final JdbcTemplate jdbc;private final ObjectMapper json;private final HttpClient http=HttpClient.newBuilder().version(HttpClient.Version.HTTP_1_1).connectTimeout(Duration.ofMillis(500)).build();private final String aiUrl;
 public IntelligenceController(JdbcTemplate jdbc,ObjectMapper json,@Value("${hospital.ai-service-url}")String aiUrl){this.jdbc=jdbc;this.json=json;this.aiUrl=aiUrl;}
 public record Candidate(@NotBlank String candidateId,@DecimalMin("0")@DecimalMax("1")double preferenceFit,@DecimalMin("0")@DecimalMax("1")double availabilityQuality,@DecimalMin("0")@DecimalMax("1")double workloadBalance){}
 public record RankRequest(@NotEmpty@Size(max=100)List<@Valid Candidate> candidates){}
 public record Feedback(@NotBlank String candidateId,@NotBlank String modelVersion,boolean accepted,@Size(max=500)String comment){}
 @PostMapping("/rank") public ResponseEntity<JsonNode> rank(@Valid@RequestBody RankRequest request){try{var payload=json.createObjectNode();var items=payload.putArray("candidates");request.candidates().forEach(c->{var n=items.addObject();n.put("candidate_id",c.candidateId());n.put("preference_fit",c.preferenceFit());n.put("availability_quality",c.availabilityQuality());n.put("workload_balance",c.workloadBalance());});var call=HttpRequest.newBuilder(URI.create(aiUrl+"/v1/rank")).timeout(Duration.ofMillis(500)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(payload))).build();var response=http.send(call,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100==2)return ResponseEntity.ok().header("X-AI-Fallback","false").body(json.readTree(response.body()));}catch(Exception ignored){}return ResponseEntity.ok().header("X-AI-Fallback","true").body(fallback(request));}
 @PostMapping("/feedback")@ResponseStatus(HttpStatus.CREATED) public Map<String,Object> feedback(Authentication auth,@Valid@RequestBody Feedback f){UUID id=UUID.randomUUID();jdbc.update("insert into recommendation_feedback(feedback_id,user_id,candidate_id,model_version,accepted,comment) values (?,?,?,?,?,?)",id,user(auth),f.candidateId(),f.modelVersion(),f.accepted(),f.comment());return Map.of("feedbackId",id,"recorded",true);}
 private ObjectNode fallback(RankRequest request){var root=json.createObjectNode();root.put("modelVersion","api-fallback-v1");root.put("featureVersion","v1");root.put("synthetic",true);root.put("fallback",true);var ranked=new ArrayList<Candidate>(request.candidates());ranked.sort(Comparator.<Candidate>comparingDouble(c->-(.5*c.preferenceFit()+.3*c.availabilityQuality()+.2*c.workloadBalance())).thenComparing(Candidate::candidateId));var out=root.putArray("rankings");ranked.forEach(c->{var n=out.addObject();n.put("candidateId",c.candidateId());n.put("score",Math.round((.5*c.preferenceFit()+.3*c.availabilityQuality()+.2*c.workloadBalance())*1_000_000d)/1_000_000d);n.put("confidence","FALLBACK");n.putArray("reasons").add("deterministic policy ranking");});return root;}
 private UUID user(Authentication a){return UUID.fromString(a.getName());}
}
