package com.careflow.hospital.doctors;
import com.careflow.hospital.audit.AuditService; import com.careflow.hospital.departments.DepartmentRepository; import com.careflow.hospital.identity.*; import com.careflow.hospital.shared.DomainException; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class DoctorOnboardingService {private final DoctorApplicationRepository applications;private final DoctorRepository doctors;private final DepartmentRepository departments;private final AppUserRepository users;private final AuditService audit;
 public DoctorOnboardingService(DoctorApplicationRepository a,DoctorRepository d,DepartmentRepository dep,AppUserRepository u,AuditService audit){applications=a;doctors=d;departments=dep;users=u;this.audit=audit;}
 @Transactional public DoctorDtos.ApplicationView apply(UUID userId,DoctorDtos.Apply request){if(applications.existsByUserId(userId)||doctors.existsByUserId(userId))throw new DomainException(HttpStatus.CONFLICT,"DOCTOR_APPLICATION_EXISTS","A doctor application already exists for this account.");if(applications.existsByLicenseNumberIgnoreCase(request.licenseNumber().strip()))throw new DomainException(HttpStatus.CONFLICT,"LICENSE_ALREADY_SUBMITTED","This license number has already been submitted.");var department=departments.findById(request.departmentId()).filter(d->d.isActive()).orElseThrow(()->new DomainException(HttpStatus.BAD_REQUEST,"DEPARTMENT_UNAVAILABLE","The selected department is unavailable."));var application=applications.save(new DoctorApplication(userId,request.fullName().strip(),request.specialization().strip(),department.getId(),request.qualifications().strip(),request.experienceYears(),request.licenseNumber().strip().toUpperCase(Locale.ROOT)));audit.record(userId,"DOCTOR_APPLICATION_SUBMITTED","DOCTOR_APPLICATION",application.getId(),"SUCCESS");return view(application);}
 @Transactional(readOnly=true) public List<DoctorDtos.ApplicationView> pending(){return applications.findAllByStatusOrderByCreatedAtAsc("PENDING").stream().map(this::view).toList();}
 @Transactional(readOnly=true) public DoctorDtos.ProfileView profile(UUID userId){var doctor=doctors.findByUserId(userId).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"DOCTOR_NOT_FOUND","Doctor profile was not found."));var department=departments.findById(doctor.getDepartmentId()).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"DEPARTMENT_NOT_FOUND","Doctor department was not found."));return new DoctorDtos.ProfileView(doctor.getId(),doctor.getDoctorNumber(),doctor.getFullName(),doctor.getSpecialization(),department.getId(),department.getName(),doctor.getLicenseNumber(),doctor.getExperienceYears(),doctor.getVerificationStatus(),doctor.isActive());}
 @Transactional public DoctorDtos.ApplicationView review(UUID adminId,UUID applicationId,String decision){DoctorApplication application=applications.findById(applicationId).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"DOCTOR_APPLICATION_NOT_FOUND","Doctor application was not found."));try{if("APPROVE".equals(decision)){AppUser user=users.findById(application.getUserId()).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Applicant account was not found."));application.approve(adminId);doctors.save(new Doctor(application));user.addRole("DOCTOR");users.save(user);}else application.reject(adminId);}catch(IllegalStateException e){throw new DomainException(HttpStatus.CONFLICT,"APPLICATION_ALREADY_REVIEWED",e.getMessage());}audit.record(adminId,"DOCTOR_APPLICATION_"+decision,"DOCTOR_APPLICATION",applicationId,"SUCCESS");return view(application);}
 private DoctorDtos.ApplicationView view(DoctorApplication a){return new DoctorDtos.ApplicationView(a.getId(),a.getUserId(),a.getFullName(),a.getSpecialization(),a.getDepartmentId(),a.getExperienceYears(),a.getLicenseNumber(),a.getStatus(),a.getCreatedAt());}}
